### ISSUE TITLE
All ToDo's

### ISSUE THREAD

**Issue by AlexRyzhkova** [AlexRyzhkova/MarryMe_App#10]
# User story
As a user 
I want to be able to see my To-Dos on the To-Do page
so I can manage my tasks. 

# Description

# Material

# Done?
- [x] Create a toDo component
- [x] Create a To-Do list  with all ToDo items
- [ ] Create a To-Do's page
- [x] Add a completed button
