### ISSUE TITLE
Create a new ToDo

### ISSUE THREAD

**Issue by AlexRyzhkova** [AlexRyzhkova/MarryMe_App#11]
# User story
As a user 
I want to be able to click on a plus button, 
so I can create a new ToDo and add it to the list. 

#Description

#Material

#Done?
- [x] Create a form for a new ToDo
- [x] Create an input field for a title 
- [x] Add a submit button to save an information
- [ ] Create a plus button 
- [ ] Add a link to the new ToDo page  to the button
