### ISSUE TITLE
ToDo detail page

### ISSUE THREAD

**Issue by AlexRyzhkova** [AlexRyzhkova/MarryMe_App#16]
# User story
As a user 
I want to be able to click on a single ToDo from the list   
so I can add information or delete a ToDo. 

# Description

# Material

# Done?
- [x] Create a detail page for single ToDo 
- [x] Add an input field for the other information
- [x] Add a delete function

**Comment by AlexRyzhkova** [comment]
Fix #28
